id: I464B18DD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T23:32:39+00:00'
last_modified: '2022-06-08T05:22:50.649392+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ294459
  title: པདྨ་འོད་གླིང་གི་བཅའ་ཡིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    07D3:
      image_group_id: I4CZ294591
      title: ''
      total_pages: 24
      order: 1
      base_file: 07D3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
