id: P005624
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ294459
  title: པདྨ་འོད་གླིང་གི་བཅའ་ཡིག
  author: ''
  volumes:
    3c53384ee6544956a5ba429115f737f3:
      image_group_id: I4CZ294591
      title: ''
      volume_number: 1
      total_pages: 24
